scrape_configs:
  - job_name: 'sample_monitoring'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['host.docker.internal:9898']
      - targets: ['host.docker.internal:4000']